advance/advance.mak

Distributions really need this.

Support make install DESTDIR=/foo just like Automake does

---

src/vidhrdw/djboy.c

Fix gfx for DJ Boy

---

src/vidhrdw/toaplan1.c

This nets us a major performance boost

Use Toaplan1 vidhrdw from ShmupMAME v3.0

---

src/drivers/contra.c

furrtek Added Konami 007452 multiplier/divider fixes rolling mines and bullet trajectories on 3D stages in contra
Rather than add a whole new device im just hooking it directly into the Contra driver for this core
Combat School Flak Attack and WACLeMans also use this but for now im focusing on Contra as
the game improvements are known
Whereas with the others the benefits over the original simulations are not as yet known if indeed there are any.

Contra protection improvements

---

src/drivers/batman.c

Haze, Mame dev team, FBN dev and the MAME2003+ dev team

New working game Marble Madness II

---

src/drivers/deco32.c
src/drivers/m92.c
src/drivers/mystwarr.c
src/vidhrdw/deco32.c

Fix for UCCOPSJ and UCCOPSAR attract mode.
Fix for VIOSTORM attract mode.
Fix for FGHTHIST Ryoko's stage.
Many thanks to Bryan, Dink and Stevie!

Fix for UCCOPS, VIOSTORM, FGHTHIST

---

src/drivers/tecmosys.c

Two new working games Tecmo System

---

drivers/denjinmk.c
drivers/legionna.c
includes/denjinmk.h
machine/seicop.c
machine/seicop.h
mame.mak
sndhrdw/seibu.c
vidhrdw/denjinmk.c

Denjin Makai (Ghost Chaser Densei) is now playable, thanks to Arcadez

Optimized driver for Denjin Makai

---

src/drivers/segac2.c

Head On Channel
OOPArts
SegaSonic Bros

Add three recently released Sega C2 prototypes

---

src/sound/ics2115.c

This also improves the sound more generally for all the other PGM games.
we're keeping the original timers from MAME106 rather the adjusted ones from shmupmame otherwise the games take a  big hit in performance .
Big thanks to the shumpmame project for the code

Vastly improve the sound for the Cave PGM games

---

src/drivers/segas18.c

Also fixed the parent set of Alien Storm to make it playable
With a huge thanks to grant2258

New Working Clockwork Aquario (Prototype)

---

src/drivers/slapfght.c

0.138u3: Phil Bennett and Dr. Decapitator hooked up Slap Fight/Alcon 68705 MCU

Add the protection MCU for the official Alcon / Slap Fight sets

---

src/drivers/toaplan2.c

With thanks to dink for advice as per how to hookup the mcu  inputs for TekiPaki using the older codebase.

Hookup the HD647180 sound mcu for Ghox, TekiPaki and Whoopee!

---

src/drivers/megasys1.c

Fixed gfx priorities 64th. Street - A Detective Story and Chimera Beast by hooking up the missing prios proms 
Hooked up sprite buffering to fix some shaky sprites which affected all games on this system 
Added new correct sound rom for Kick Goal
Added support for In Your Face

Megasys1 gfx fixes and new working game

---

src/drivers/pacman.c

Thats the banking fixed @arcadez2003 and @amadvance.

fix mspactwin

---

src/drivers/exerion.c

This will prevent the game from ending regardless of how many lives you have left if you die after the 1st bonus round.

Exerion Protection fix

---

src/vidhrdw/undrfire.c

0.125u2: Phil Bennett fixed black pixel patches present in the TC0100SCN fg layer of Under Fire.

Video changes for cbombers and a fix for underfire

---

src/drivers/8080bw.c

0.132u2: Hau fixed Steel Worker coinage (inserting a coin at certain moments during attract mode results in a broken game).
0.132u1: Hau, Chack'n and Dumping Union added 'Steel Worker' (Taito 1980).

Add Taito's Steel Worker

---

src/vidhrdw/flower.c

Tilemaps were incorrectly reversed

 Fix some graphical niggles in Flower {dink}

---

src/drivers/topshoot.c

Also added the inputs for Top Shooter it should be playable now although it's just a medal game

Let's see if Super Bubble Bobble Megadrive bootleg will work

---

src/drivers/genesis.c

Fix Missing sfx for Super Bubble Bobble (Sun Mixing)

---

src/drivers/topshoot.c

Disabled for now while i track for errors

Added Sonic The Hedgehog 3 Arcade Bootleg

---

src/sound/ym2151.c

Namely Mustache Boy and the Lost Castle In Darkmist
First we need to tweak some timer code in ym2151.c  so the sound doesn't  cut out in the aformentioned games
MAME WIP
0.112u4: Nicola Salmora, Lord Nightmare and Ernesto Corvi added T5182 support, which gives sound to Darkmist, Mustache Boy and Panic Road. Added Z80 (3579545 Hz) CPU2 and YM2151 (3579545) sound. Added T5182 rom (cpu2) and 2nd coin slot.

Let's add full sound and music for two games which are currently silent

---

src/drivers/m62.c

Horizon
Kid Niki Radical Ninja
Spelunker 1 and 2
With thanks to MAME2003+ and FBN dev teams

Add IREM tr606 drumkit sample support for the following games

---

src/drivers/chaknpop.c

0.187: Replaced MCU simulation with new M68705 dump [Team Japump, Chack'n, Hau]. Added M68705 (3MHz) CPU3.

Hookup the proper protection mcu for Chack 'n pop

---

src/drivers/gaelco2.c

0.173: System11 added clone Touch & Go (Korea, unprotected). This is the first working set for this game, all other sets are protected. Improved Touch & Go video. Updated stream on read in Gaelco sound driver, Touch & Go still seems to forget to play sounds sometimes tho, like one of the channels gets stuck busy? [David Haywood].

Add unprotected set for Touch And Go

---

src/vidhrdw/gaelco2.c

Also enabled the single screen hack for the two screen games.

Touch And Go requires some video changes

---

src/drivers/rohga.c

Also fixed character selection in Darkseal 2 / Wizard Fire

Attempt to support Hangzo and add Wolf Fang Kuhga - 2001

---

src/drivers/metro.c

0.155: Brian Troha figured out one dipswitch in Mouse Shooter GoGo. Added 'Allow P2 to Join Game' dipswitch.
0.137u1: Stefan Lindberg, Luca Elia and The Dumping Union added 'Mouse Shooter GoGo' (Metro 1995).

New working Mouse Shooter GoGo

---

src/drivers/ladybug.c

0.232: Frank Palazzolo added 'Mrs. Dynamite' (Universal 1982).

Add Mrs Dynamite

---

src/vidhrdw/ssv.c

Fixed graphical corruption on left side of screen stage 3 onwards in Storm Blade and all stages in Ultra X Weapons [MAMEDev, arcadez]
Added some alt sprite drawing to the ssv video to prevent performance drops in some SSV games after the above updates [BritneysPAIRS]
EDIT this commit also contains...
https://github.com/libretro/mame2003-plus-libretro/commit/ed9a8684e987e39e1981a1ec0a9412663f3f47ff

Backport some gfx fixes for Storm Blade and Ultra X Weapons

---

src/vidhrdw/undrfire.c

Add Gunsights for Taito's Underfire

---

src/drivers/sg1000a.c

0.109u1: Tomasz Slanina and Guru added 'Doki Doki Penguin Land' (Sega 1985).
25th September 2006: Tomasz Slanina - Added (recently dumped by Guru) Doki Doki Penguin Land to Sega sg1000a driver.

Another bonus Doki Doki Penguin Land

---

src/drivers/nmk16.c

Protection is properly emulated for all games
many sound and video improvements
Task Force Harrier now playable
Added unprotected version of Hacha Mecha Fighter
as the protected set has many issues related to the protection sim.

Update nmk16 driver

---

src/vidhrdw/nmk16.c

Video improvements and the protection is hooked up

Update nmk16 video to match up with the new driver

---

src/drivers/snk.c

Original code via BritneysPAIRS with some changes by me for this core
Dougou Souken
0.121u1: Changed description of clone 'Dogou Souken (Joystick bootleg)' to 'Dogou Souken (Joystick hack bootleg)'.
0.112u1: Removed Dial control.
0.78u5: Pierpaolo Prazzoli added clone Dogou Souken (Joystick bootleg).
Guerilla War
0.127u7: Stephane Humbert checked inputs and dipswitches via Z80 code analysis for Guerrilla War and clones. Added missing support of normal joystick for player 2 in clone Guerrilla War (Joystick hack bootleg).
0.127u2: Nicola Salmoria and Roberto Zandona changed the default bootleg Guerrilla War PCB to be joystick only, and removed code duplication. Changed description of clone (bootleg) to 'Guerrilla War (Joystick hack bootleg)'.
0.127u1: fixed input and added DIP locations …

Guerilla War Ikari Warriors and TNK3 enable the joystick bootlegs

---

src/drivers/seta.c

Strike Gunner S.T.G add missing button 3 inputs
Used to merge both ships into one during a two player game

Support Downtown Joystick Bootleg

---

src/drivers/coolpool.c

Plus fixed missing input "English" for Cool Pool

Add 9 Ball Shootout Championship Edition

---

src/machine/kaneko16.c

fix brapboys

---

src/drivers/nmk16.c

Attempt to fix Hacha Mecha Fighter (unprotected)

---

src/vidhrdw/fuukifg3.c

From MAME 112.u2 forgot to add the fix

Fix some gfx niggles for Asura Buster

---

src/drivers/safarir.c

Safari Rally fix colours and add sound sample support

---

src/drivers/rungun.c

To prevent bad rom check on boot

Add default eeprom for Run And Gun

---

src/drivers/taito_f2.c

megablst and clones: Shield powerup aura on option is missing {HAZE]

Metal Blast Fix missing gfx effect

---

src/drivers/silkroad.c

Adds some missing SFX and speech to the game eg when the special moves trigger "ice storm" etc etc
MAME WIP
0.129u5: Angelo Salese fixed sound not playing in Silkroad. 0.129u4: Pierpaolo Prazzoli added effect sound banking to Silkroad.

Sound improvements for The Legend Of Silkroad

---

src/vidhrdw/cps1.c

Strider etc etc should look much nicer now

Improve the starfield emulation for the CPS1 games that use it

---

src/drivers/esd16.c

With thanks to iq_132 and BritneysPAIRS

Update esd16.c fix sound rom loading + gfx fixes + 2 new games

---

src/vidhrdw/aerofgt.c

Spinal Breakers
0.128u4: Roberto Zandona fixed priority issues in Spinal Breakers.
Turbo Force
0.109: Canim fixed some sprite priorities problems in Turbo Force (the problem is related with the final enemy in stage 3, which is moving along the level under the floor)

Fix various graphical niggles for the video system games

---

src/drivers/williams.c

0.115u1: Aaron Giles fixed sound in Inferno after all these years. Sadly, it required a hack.

Fix broken sounds for Inferno

---

src/drivers/topshoot.c

Jurassic Park and Twinkle Tale
With thanks to Mahoneyt944 for adding the coinup hacks for both games.

Add two more bootlegs

---

src/drivers/snowbros.c

Come Back Toto and Puzzle Break

Might as well add these ones
