amadvance/advancemame

- mess/vidhrdw/apf.c
The variable apf_ints is defined as unsigned char. Trying to access it as unsigned int caused the following error:
```
| obj/mess/linux/blend/apf.a(apf.o): In function `apf_vsync_int':
| .../mess/vidhrdw/apf.c:30:(.text+0x60): relocation truncated to fit: R_AARCH64_LDST32_ABS_LO12_NC against symbol `apf_ints' defined in COMMON section in obj/mess/linux/blend/apf.a(apf.o)
| .../mess/vidhrdw/apf.c:30: warning: One possible cause of this error is that the symbol is being referenced in the indicated code as if it had a larger alignment than was declared where it was defined.
```
> apf_vsync_int: fix invalid access to apf_ints variable

- src/sndhrdw/taito_f3.c
0.144: Angelo Salese added a preliminary ES5510 DSP DRAM input/output latches support in Taito F3 driver, fixes sound in Riding Fight.
7th November 2011: Angelo Salese - Implemented ES5510 DSP DRAM latches to Taito F3 driver, this adds full sound to Riding Fight.
0.144: Angelo Salese added a preliminary ES5510 DSP DRAM input/output latches support in Taito F3 driver, fixes sound in Ring Rage.
7th November 2011: Angelo Salese - Implemented ES5510 DSP DRAM latches to Taito F3 driver, this gives correct sound to Ring Rage without going into test mode first.
> Fix sound in Ring Rage and add sound support for Riding Fight

- src/vidhrdw/midtunit.c
This fix from MAME114 will stop the game randomly crashing at the end of a level
> Fix random crash in Rampage World Tour

- configure.ac
Explicitly blank flags are valid.
> Don't use auto CFLAGS/LDFLAGS if they are set but blank

- src/drivers/cave.c
0.127u1: ShimaPong hooked up sound CPU communications in Power Instinct 2. This enables synchronized dancing for the background characters.
> Fix background character movements for Power Instinct 2 and Legends

- advance/emu.mak
- advance/osd/dvg.c
- advance/osd/dvg.h
- advance/osd/glue.c
- advance/osd/video.c
Added support for an upcoming hardware vector generator for Advance Mame.   The software added registers as an aux renderer.
Added new keys in advancemame.rc:
vector_aux_renderer [none] [dvg]                 ;  Enables the USB-DVG aux renderer or not.
vector_aux_renderer_dual_display [yes][no]  ; Allows for bitmap and vector display at the same time or not
vector_aux_renderer_port [serial port]          ;  Serial port name such as /dev/ttyACM0
> Added USB-DVG vector generator board support

- src/machine/gaelco2.c
0.171: Samuel Neves and Peter Wilhelmsen figured out algorithm and replaced Snow Board Championship lookup table with proper emulation of device.
0.170: Charles MacDonald and David Haywood added 8GB decrypt table to Snow Board Championship and clone - Game now playable.
> Hook up the decryption tables for Snow Board Championship

- src/drivers/gaelco2.c
0.171: Samuel Neves and Peter Wilhelmsen figured out algorithm and replaced Snow Board Championship lookup table with proper emulation of device.
0.170: Charles MacDonald and David Haywood added 8GB decrypt table to Snow Board Championship and clone - Game now playable.
> New Working Game Snow Board Championship

- src/drivers/cosmic.c
0.128u1: T. Bellm added samples support to Cosmic Alien. Added DAC and Samples sound (backgr, extend, divea, diveb1-6, fire, loudexp, smallexp and coin.wav).
> Hook up DAC and sample sound support for Cosmic Alien

- src/drivers/djboy.c
0.116u4: Phil Stroffolino fixed DJ Boy - Game now playable. Updated djboy driver [Phil Stroffolino]: Support for DJ Boy (Japan); same MCU, but ROM banking bits need to be XOR'd. Fixed state handling for game over/win transitions. Fixes for dipswitches. Added coinage support.
0.116u3: Updated DJ Boy driver to almost fully playable state [Phil Stroffolino]. Changed clock speed of the 2x OKI6295 to 1.5MHz. Fixed dipswitches.
With thanks to IQ_132
> New Working Game DJ Boy

- src/drivers/m107.c
Sort graphical tile layer problem which was obscuring the screen, some graphical niggles still remain however, hook up the sound and music.
0.140u3: Angelo Salese added reset line trigger from main to sound CPU in Irem M107 driver
Game was totally unplayable in MAME106, now it works from beginning to end, with thanks to BritneysPAIRS for the gfx improvements
> New working game Fire Barrel

- src/vidhrdw/taito_f3.c
>  Fix the lights dont go out when shot in Elevator Action II / Returns

- advance/osd/dvg.c
- advance/osd/glue.c
Make sure the clip coordinates fall within the display screen coordinates
> corrected clipping issue with battlezone, major havoc

- advance/osd/dvg.c
- advance/osd/glue.c
USB transfer now done in chunks of 1024 bytes to solve some issue with long USB transfers
Determine the best rendering quality for games
In quiet mode, and especially while having only the vector display, we can't display the exit menu on the other screen.
> Fix USB issue and did various optimizations

- advance/dos/wss.c
- advance/svgalib/svgalib.c
- src/machine/eeprom.c
* `advance/dos/wss.c`: `get_played_sample_count()` was missing parentheses, causing the function address to be compared instead of the return value.
* `advance/svgalib/svgalib.c`: `memset` argument order was incorrect, causing the structure to be uninitialized instead
* `src/machine/eeprom.c`: indent order of debug print triggered a spurious warning about "if" guarding
> Fix some minor issues in advancemame compilation.

- src/cpu/tms32031/32031ops.c
0.146u2: Daniel Filner fixed Off Road Challenge - Game now playable. Two TMS32031 CPU1 fixes: Don't set underflow when doing a floating point subtract that results in 0. Don't overwrite the exponent during a FIX operation
Code has been heavily modded to work with this core
> Backport a TMS32031 fix for Midway's Off Road Challenge

- src/drivers/lwings.c
0.136u3: Mamesick and Angelo Salese fixed long-standing (day one?) bug with ADPCM samples in Trojan and clone Tatakai no Banka.
> Fix sound problems in Trojan / Tatakai No Banka

- src/cpu/m68000/m68kcpu.c
- src/cpu/m6805/m6805.c
- src/cpu/z180/z180op.c
- src/drivers/cosmic.c
- src/drivers/quasar.c
- src/sound/discrete.c
- src/sound/ym2413.c
- src/vidhrdw/konamiic.c
Whitespace change in drivers/cosmic.c, sound/discrete.c, vidhrdw/konamiic.c
Fixes some cc warnings about improperly guarded "else" conditions.
Sound cleanup and fix for an incorrect switch fallthrough in drivers/cosmic.c
(https://github.com/mamedev/mame/commit/4298ce18fb33d5935231a83bcf1f60289eb6b09c)
Fix for m68000 save-states in cpu/m68000/m68kcpu.c
(https://github.com/mamedev/mame/commit/507ca2d27520118151a2556d96b9a15aac768876)
Fix for an alway-false comparison in sound/ym2413.c
(https://github.com/mamedev/mame/commit/3f884db5bdf00fcdfb91c425caa1331f74d14944)
Fix for array-index-out-of-bounds in cpu/m6805/m6805.c
Fix for array-index-out-of-bounds in cpu/z180/z180op.c
> Several fixes for compile warnings, backported from more recent MAME

- advance/linux/event.c
Using EV_MAX causes a stack smashing failure when compiled with -fstack-protector.
> Use bitmask size not EV_MAX for EVIOCGBIT ioctl.

- src/vidhrdw/buggychl.c
MAME WIP
Kale Fixed background pen and clipping enable (fixes title screen and stage 3 graphics).
0.138u2: hap improved the sky in Buggy Challenge, the in-game foreground statusbar and speedometer don't clip it anymore and it's a gradient of azure->turquoise now instead of azure->black.
> Fix some broken gfx in Buggy Challenge

- src/drivers/gaelco.c
Prevents Thunder Hoop from crashing on level 4 and insert coin text sticking on screen after you continue in Squash, also fixed priorities in Thunder Hoop.
With thanks to FBN And MAME Dev.
> Thunder Hoop Fixes

- src/drivers/toaplan2.c
This uses a Z80 rather than an encrypted V25 for the sound hence it does not require those Toaplan samples
> New working Dogyuun (8/25/1992 location test)

- src/drivers/contra.c
As per PCB info switch the main cpu to a HD6309 and change the clock speeds on both CPU's to match measured values.
Removes slowdowns in game and fixes a possible crash after you defeat the boss at the end of the stage containing the second  enemy base.
Also fixed sprites sticking on the screen
> More fixes for Contra / Gryzor

- src/drivers/wilytowr.c
0.138u1: hap fixed very low background music in Wily Tower.
0.126u5: Tomasz Slanina and Stefan Lindberg added sprite wrapping to Irem M63 driver.
0.126u3: Irem M63 [Stefan Lindberg]: Adjusted 2x AY-3-8910A frequencies to proper 1.5MHz.
0.125u6: Tomasz Slanina added sound emulation to Fighting Basketball. Changed region cpu2 ($1000) to user1 ($0).
0.125u6: Tomasz Slanina added sound emulation to Wily Tower and clone Atomic Boy.
0.125u3: Stefan Lindberg added clone Atomic Boy (revision B). Changed Z80 CPU1 and I8039 CPU2 clock speeds to 3MHz. 
0.124: RansAckeR fixed watchdog resets.
0.123u6: Machone and RansAckeR Added dipswitches 'Bonus Points Rate.
0.122u6: Changed I8039 CPU2 clock speed to 8MHz.
> Add sound for Atomic Boy / Wilytower fix sound for Fighting Basketball

- src/drivers/dkong.c
Also added sound support for Special Forces 1 and 2
With thanks to iq_132 who originally reworked the braze decryption
> New Working Game Donkey Kong II Jumpman Returns

- src/drivers/armedf.c
All the games look alot prettier as they're now using the sprite colour clut, both versions of Legion  are now playable and i've added the workaround for the timer bug in Kozure Ookami which caused the game to hang this hack can be turned off or on via the dips
MAME WIP
0.159: Angelo Salese added protection note about Kozure Ookami, for future reference. Patched timer over bug in Kozure Ookami. Remarked game as working state, see source notes for further info. Added 'Infinite Timer (Cheat)' dipswitch.
23rd April 2011: Angelo Salese - Discovered and implemented sprite color cycling effects in ArmedF driver. That's a RAM-based clut table that look-ups via a byte in the sprite defs. As you can see from the YT vids, it's used for doing neat effects such as explosions / bonus colors etc. in …
> Backport some improvements for armedf hardware

- src/drivers/pacman.c
* Added support for rare, Ms. Pacman Twin (mspactwin) simultaneous 2 player play [arcadez, grant2258, mahoneyt944]
> Ms. Pacman Twin

- src/drivers/lethal.c
0.139u2: Roberto Zandona hooked up some K053244 register to Lethal Enforcers. Fixed missing flip bits used for the tiles (P2 start screen, reload indicator).
0.106u12: Cananas fixed the fire button INPUT_PORT of player2 in Lethal Enforcers.
> Lethal Enforcers improve emulation

- src/vidhrdw/konamiic.c
0.143u7: Roberto Zandona fixed Lethal Enforcers external rowscroll not hooked up correctly (1st attract level, highscores) and some priority issues / sprite placement issues.
> Small graphical hack for Lethal Enforcers

- src/drivers/freekick.c
0.143u5: Charles MacDonald and The Dumping Union fixed Free Kick - Game now playable. Added maincpu rom (ns6201-a_1987.10_free_kick.cpu - 52k).
> Free Kick make the official version work

- src/drivers/kaneko16.c
0.170: ShouTime added 'Wing Force (Japan, prototype)' (Atlus 1993). Wing Force sound fixes and change VSync [trap15]: Sound was clearly incorrect before, now it sounds much closer to PCB video. Also changed the VSync rate to 59.1854 like Fujiyama Buster and B.Rap Boys, as it makes the title theme exit at the same point as the PCB video.
> New Working Game Wing Force

- src/drivers/cps2.c
0.112: Nicola Salmoria added 'Hyper Street Fighter 2: The Anniversary Edition (Asia 040202)' (Capcom 2004).
22nd December 2006: Razoola - Released XOR 125 for 'Hyper Street Fighter II (Asia 040202)'. Dedicated to all Street Fighter fans.
> Hyper Street Fighter II

- src/drivers/undrfire.c
0.125u1: Phil Bennett fixed Chase Bombers - Game now playable. Improved sprites. Hooked up steering wheel input. Unified memory maps and tidied up some code. Changed ES5505 sound clock rate to 15238050 Hz. Removed Player 2 and added button 5.
0.124u1: Bryan McPhail added 'Chase Bombers' (Taito Corporation 1994).
3rd February 2008: Guru - We won a rare Taito Chase Bombers auction on ebay (which I dumped about a week ago) and a couple of others in Japan.
> New one Chase Bombers

- src/vidhrdw/groundfx.c
0.125u2: Phil Bennett fixed black pixel patches present in the TC0100SCN fg layer of Ground Effects.
> Small gfx fix for Taito's Super Ground Effects

- src/drivers/lastduel.c
0.167: system11 added Led Storm Rally 2011 (World). 'Guru added correct sprite rom dumps to clone (US). David Haywood adjusted the rom loading / gfxdecoding in the driver to accommodate the correct ROMs for Led Storm Rally 2011 (US) - Game now playable.
0.151: Various fixes [Phil Bennett]: Fixed 'Led Storm Rally 2011 (US)' sprite ROM order (though bad sprites remain due to incorrect ROMs). Changed input from 1 to 3 buttons.
0.133u1: David Haywood marked graphics ROMs on Led Storm Rally 2011 (US) as bad, as they cannot possibly be the right ones for this set.
0.132u4: Brian Troha updated 'Led Storm Rally 2011' with new roms as per Guru's info. Marked this game as GAME_IPERFECT_GRAPHICS due to the bad sprite etc.
0.124u3: Bryan McPhail added 'Led Storm Rally 2011' (US).
> Add two unique versions of 1943 and Led Storm

- src/drivers/mexico86.c
Kick N Run 
0.222: Hooked up 'Kick and Run' MCU - Game now playable [dink]. Added 'Demo Sounds' dipswitch. Changed VSync to 59.185606 7Hz.
0.221: Added MCU dump to Kick and Run, not yet working [Sean Riddle]. Replaced Mexico86 bootleg M68705 CPU3 with M6801.
Kiki Kai Kai
0.262: Added KiKi KaiKai M6801 MCU ROM dump [Madov, Raki, Travis Goodspeed].
> Hook up the M6801 MCU's for Kiki Kai Kai and Kick And Run

- src/machine/mexico86.c
And nuke the dodgy and broken MCU sim for Kiki Kai Kai game can now be considered 100% in the emulation dept
> Finish hooking up the M6801 for Kiki Kai Kai and Kick And Run

- src/drivers/fuukifg3.c
0.112u2: David Haywood and Guru added 'Asura Buster - Eternal Warriors (Japan)' (Fuuki 2000).
> Add Asura Buster to fuukifg3.c

- src/drivers/flower.c
0.126u2: David Haywood merged CPU0 and 1 memory maps in Flower, improved interrupt generation. This fixes starting a game doesn't always register.
0.125u8: Brian Troha fixed Flower dipswitches Added dipswitches 'Energy Decrease', 'Enemy Bullets', 'Demo Sounds' and 'Keep Weapon Items When Destroyed'.
> Some fixes for Flower

- src/sndhrdw/flower.c
Enabling this little hack will prevent certain sample sounds from playing constantly
>  Improve sound for Flower

- src/drivers/decocass.c
0.147u2: Tornadoboy added Angler Dangler (DECO Cassette).
0.146u2: SRI, Charles MacDonald and Team Japump added 'Fishing (DECO Cassette)' (Data East 1982).
20th June 2012: Smitdogg - Fishing (the Japan region version of Angler Dangler) is dumped.
> Add Angler Dangler / Fishing to decocass.c

- src/drivers/genesis.c
Required for Aladdin and Bare Knuckle 3 arcade bootlegs
> Add some code from MESS to emulate the Genesis gamepads

- src/drivers/topshoot.c
Aladdin, Bare Knuckle 2 + 3 and Sonic The Hedgehog 2
Not enabled in the build as yet.
> Add support for some arcade bootlegs using genesis hardware

- src/drivers/jollyjgr.c
0.138u2: Angelo Salese fixed priorities in Frog & Spiders.
0.138: hap added missing projectiles to Frog & Spiders, game is playable now. Changed description to 'Frog & Spiders (bootleg?)'.
0.137u4: Siftware added 'Frog & Spiders (bootleg)' (Taito Corporation 1981).
1st May 2010: Smitdogg - Siftware dumped a bootleg of Frog & Spiders (might use all original unhacked Taito data though?).
> Attempt to support Taito's Frog And Spiders

- src/drivers/dblewing.c
0.129u3: Angelo Salese improved the sound in Double Wings by appling the same handling of Night Slashers (they are actually similar if not same memory map).
0.128u4: Angelo Salese fixed several protection issues with Double Wings, improved video and sound. Added 'Territory' dipswitch.
21st November 2008: Angelo Salese - Looking at Double Wings protection, first of all to fix the protection jump vectors in it. Protection works in a easier way than expected, to say in the simplest words I can use it's a "fan type jump vectors" (i.e. only a few possible results are expected).
0.126u4: Fabio Priuli added DIP locations to Double Wings.
0.106u3: Brian Troha, Guru and Yasuhiro Ogawa updated dipswitches in Double Wings. These dips are read using the protection, thus they don't currently have the …
> Improve emulation for Double Wings

- src/machine/dec0.c
Emulated Sly Spy RNG device at $31c00d. This makes gameplay behave very differently than before, game extensively uses this port to mix up stuff especially with the bosses. [Angelo Salese]
> Data East's Secret Agent / Sly Spy add RNG protection emulation

- src/drivers/renegade.c
Big thanks to dink for helping me out with this.
MAME WIP
Nekketsu Kouha Kunio-kun
0.190: Lord Nightmare and ShouTime fixed corrupt bytes in the MC68705 dump of clone Nekketsu Kouha Kunio-kun (Japan) after re-analysis of raw dump data.
0.187: Replaced MCU simulation in clone Nekketsu Kouha Kunio-kun (Japan) with actual M68705 dump [ShouTime, brizzo]. Soundlatch modernization [AJR].
Renegade
0.138u3: Phil Bennett and Dr. Decapitator hooked up Renegade 68705 MCU. Fixed rom names.
25th June 2010: Guru - The 68705P5 MCU (NZ-5.IC97) for Renegade has now been successfully processed (decap, de-protect & read).
> Hook up the M68705 MCU's for Renegade and Nekketsu Kouha Kunio-kun

- src/drivers/lsasquad.c
0.138u3: Phil Bennett and Dr. Decapitator hooked up Daikaiju no Gyakushu 68705 MCU and removed MCU simulation code.
25th June 2010: Guru - The 68705P5 MCU (A74_05.IC35) for Daikaiju no Gyakushu has now been successfully processed (decap, de-protect & read).
0.106u3: Tomasz Slanina and Guru added 'Daikaiju no Gyakushu' (Taito 1986).
25th May 2006: Tomasz Slanina - Video hardware is close to 'Land Sea Air Squad' but more complicated. Working on simulation of protection MCU (68705P5). So far so good. Game is playable.
12th May 2006: Guru - Daikaizyuu no Gyakusyuu (Taito 1986) arrived from Japan.
> Support Taito's Daikaiju no Gyakushu

- src/drivers/glass.c
0.169: System11 added clone Glass (Ver 1.1, Break Edition, Version 1994) (censored, unprotected). Note: This is unprotected from Gaelco factory, the dallas etc. was never fitted, looks like it was for the Korean market (Promat stickers etc.). Verified clocks & pin7 status from real PCB [System11, The Dumping Union].
> Add an unprotected version of Glass

- src/drivers/taito_z.c
0.146u1: hap fixed Racing Beat - Game now playable. Give Racing Beat its own inputs and video update handler, the game is playable now Updated DIPs and fixed sprite-tile priority.
0.143u9: Added Battle Shark (World). ShouTime added clone Battle Shark (Japan, Joystick).
> Add joystick version of Battle Shark and get Racing Beat playable

- src/drivers/psikyosh.c
0.129: Re-added 'Tetris the Absolute The Grand Master 2' (Arika 2000) and clone 'Tetris the Absolute The Grand Master 2 Plus'.
0.99u5: This game was removed from MAME.
0.99u4: Guru added 'Tetris the Absolute The Grand Master 2' (Arika 2000) and clone 'Tetris the Absolute The Grand Master 2 Plus'.
22nd August 2005: Guru - I've just finished to dumped the tricky surface mounted roms of tgm2_plus. There were 7 used on the PCB and each one had to be removed from the PCB and mounted onto this adapter, dumped, then removed and remounted onto the PCB. Luckily I'm a patient man.
17th June 2005: Guru - Tetris GM 2 and GM 2+ arrived from Japan.
4th April 2005: Dumping Project - Our Japanese contact bought with the help of massive targeted monetary infusions from two of the world's biggest Tetris …
> Re-add Tetris The Absolute The Grandmaster 2

- src/drivers/segas16b.c
I think the original map was incorrect hence the game wont boot.
> Possible fix for Fantasy Zone II - The Tears Of Opa Opa

- src/drivers/segac2.c
Likely this is a bootleg of an early dev prototype diffs from the final retail release are as follows......
1) The intro on mine is missing the background and the music is completely different. No cool tech! 2) The game has no voices at all. Lame!
3) Weird little differences - font colors are slightly different on the "How to Play" screen and text is changed 4) Stage 4 is "Haides" and Stage 5 is "Ellis", which apparently don't exist at ALL in AC(?), just in Thunder Force 3 on the Genesis 5) Again, game ends after Stage 5
6) Stage Select is present
More info here
https://shmups.system11.org/viewtopic.php?f=1&t=66235
> ThunderForce AC add a new version with many diffs

- src/drivers/chqflag.c
0.142u3: Angelo Salese fixed protection read-back registers 0x07 and 0x0e / 0x0f in K051733 math chip, finally fixing gameplay issues in Chequered Flag. Made K051733 RNG to behave like an adder.
> Konami's Chequered Flag improve sound and K05733 protection

- src/drivers/taito_b.c
0.109u1: Mamesick fixed interrupt in Silent Dragon (in all scenes with linescrolling, the characters move in slow motion).
> Fix some slowdown issues in Silent Dragon

- src/drivers/thunderx.c
0.116u2: Shimapong fixed collision detection bug in Thunder Cross.
> Thunder Cross Fix collisions

- src/vidhrdw/gaiden.c
0.138u4: hap fixed missing screen shaking effect in Wild Fang / Tecmo Knight.
17th July 2010: Smitdogg - When I was testing the Tecmo Knight PCB we recently got for decapping, I noticed there was an effect that shook the entire screen during some jump landings and parts where enemies break through walls. The effect was missing from MAME but thanks to hap it's going to be in 0.138u4 so be sure to try out Tecmo Knight / Wild Fang in the next release to check out this effect.
> Wild Fang / Tecmo Knight emulate missing gfx effect

- src/drivers/taito_l.c
0.122u2: Changed Z80 CPU1 clock speed to 6665280 Hz, Z80 CPU3 to 4MHz and irq0_line_hold to 3, this fixes the slowdown problems.
> Fix slowdown in Taito's Fighting Hawk
